name: SCA

on:
  push:
    branches: [ "master", "main", "**" ]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      pre-scan-commands: "npm install --legacy-peer-deps --package-lock-only --ignore-scripts || true"
      additional-arguments: "--skip-unresolved"
    secrets: inherit